'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0"),  _
 Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
Partial Friend NotInheritable Class Settings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As Settings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()),Settings)
    
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
    
    Public Shared ReadOnly Property [Default]() As Settings
        Get
            
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("F")>  _
    Public ReadOnly Property LocalUsmtDriveLetter() As String
        Get
            Return CType(Me("LocalUsmtDriveLetter"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public ReadOnly Property XMLConfigMigAppChkBx() As Boolean
        Get
            Return CType(Me("XMLConfigMigAppChkBx"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public ReadOnly Property XMLConfigExcludeSysFoldersChkBx() As Boolean
        Get
            Return CType(Me("XMLConfigExcludeSysFoldersChkBx"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public ReadOnly Property XMLConfigMigUserChkBx() As Boolean
        Get
            Return CType(Me("XMLConfigMigUserChkBx"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public ReadOnly Property XMLConfigNetworkPrnChkBx() As Boolean
        Get
            Return CType(Me("XMLConfigNetworkPrnChkBx"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public ReadOnly Property BackupTargetOSChkBx() As Boolean
        Get
            Return CType(Me("BackupTargetOSChkBx"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public ReadOnly Property BackupTargetOS2ChkBx() As Boolean
        Get
            Return CType(Me("BackupTargetOS2ChkBx"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public ReadOnly Property EFSEnabledChkBx() As Boolean
        Get
            Return CType(Me("EFSEnabledChkBx"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public ReadOnly Property EFSBackupEncryptChkBx() As Boolean
        Get
            Return CType(Me("EFSBackupEncryptChkBx"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public ReadOnly Property EFSEncryptKeyString() As String
        Get
            Return CType(Me("EFSEncryptKeyString"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public ReadOnly Property EFSRestoreDecryptChkBx() As Boolean
        Get
            Return CType(Me("EFSRestoreDecryptChkBx"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public ReadOnly Property EFSDecryptKeyString() As String
        Get
            Return CType(Me("EFSDecryptKeyString"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public ReadOnly Property EFSConfigAbortRdBtn() As Boolean
        Get
            Return CType(Me("EFSConfigAbortRdBtn"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public ReadOnly Property EFSConfigSkipRdBtn() As Boolean
        Get
            Return CType(Me("EFSConfigSkipRdBtn"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public ReadOnly Property EFSConfigDecryptCopyRdBtn() As Boolean
        Get
            Return CType(Me("EFSConfigDecryptCopyRdBtn"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public ReadOnly Property EFSConfigCopyRawRdBtn() As Boolean
        Get
            Return CType(Me("EFSConfigCopyRawRdBtn"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public ReadOnly Property StorageConfigTargetWin7ChkBx() As Boolean
        Get
            Return CType(Me("StorageConfigTargetWin7ChkBx"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public ReadOnly Property StorageConfigLocalOnlyChkBx() As Boolean
        Get
            Return CType(Me("StorageConfigLocalOnlyChkBx"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public ReadOnly Property StorageConfigOverWriteChkBx() As Boolean
        Get
            Return CType(Me("StorageConfigOverWriteChkBx"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public ReadOnly Property StorageConfigNoCompressChkBx() As Boolean
        Get
            Return CType(Me("StorageConfigNoCompressChkBx"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public ReadOnly Property MonitoringConfigVerbosityChkBx() As Boolean
        Get
            Return CType(Me("MonitoringConfigVerbosityChkBx"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("7")>  _
    Public ReadOnly Property MonitoringConfigVerbosityLevel() As String
        Get
            Return CType(Me("MonitoringConfigVerbosityLevel"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public ReadOnly Property MonitoringConfigRetryChkBx() As Boolean
        Get
            Return CType(Me("MonitoringConfigRetryChkBx"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
    Public ReadOnly Property MonitoringConfigRetryTime() As String
        Get
            Return CType(Me("MonitoringConfigRetryTime"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public ReadOnly Property MonitoringConfigWaitChkBx() As Boolean
        Get
            Return CType(Me("MonitoringConfigWaitChkBx"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
    Public ReadOnly Property MonitoringConfigWaitTime() As String
        Get
            Return CType(Me("MonitoringConfigWaitTime"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public ReadOnly Property MonitoringConfigContinueOnErrorChkBx() As Boolean
        Get
            Return CType(Me("MonitoringConfigContinueOnErrorChkBx"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public ReadOnly Property MonitoringConfigSpaceEstimateChkBx() As Boolean
        Get
            Return CType(Me("MonitoringConfigSpaceEstimateChkBx"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public ReadOnly Property XMLConfigCustUsersChkBx() As Boolean
        Get
            Return CType(Me("XMLConfigCustUsersChkBx"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public ReadOnly Property XMLConfigCustAppsChkBx() As Boolean
        Get
            Return CType(Me("XMLConfigCustAppsChkBx"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public ReadOnly Property XMLConfigExcludeDrivesChkBx() As Boolean
        Get
            Return CType(Me("XMLConfigExcludeDrivesChkBx"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public ReadOnly Property MonitoringNetworkLogChkBx() As Boolean
        Get
            Return CType(Me("MonitoringNetworkLogChkBx"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public ReadOnly Property MonitoringProgressLogChkBx() As Boolean
        Get
            Return CType(Me("MonitoringProgressLogChkBx"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public ReadOnly Property BackupTargetOSWin10RdBtn() As Boolean
        Get
            Return CType(Me("BackupTargetOSWin10RdBtn"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public ReadOnly Property BackupSourceOSWin10RdBtn() As Boolean
        Get
            Return CType(Me("BackupSourceOSWin10RdBtn"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public ReadOnly Property BackupSourceOSWin7RdBtn() As Boolean
        Get
            Return CType(Me("BackupSourceOSWin7RdBtn"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public ReadOnly Property BackupTargetOSWin7RdBtn() As Boolean
        Get
            Return CType(Me("BackupTargetOSWin7RdBtn"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public ReadOnly Property StorageConfigTargetWin8ChkBx() As Boolean
        Get
            Return CType(Me("StorageConfigTargetWin8ChkBx"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public ReadOnly Property XMLConfigMigDocsChkBx() As Boolean
        Get
            Return CType(Me("XMLConfigMigDocsChkBx"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public ReadOnly Property XMLConfigConfigChkBx() As Boolean
        Get
            Return CType(Me("XMLConfigConfigChkBx"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public ReadOnly Property StorageConfigVscChkBx() As Boolean
        Get
            Return CType(Me("StorageConfigVscChkBx"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public ReadOnly Property StorageConfigHardlinkChkBx() As Boolean
        Get
            Return CType(Me("StorageConfigHardlinkChkBx"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public ReadOnly Property MonitoringConfigListFilesChkBx() As Boolean
        Get
            Return CType(Me("MonitoringConfigListFilesChkBx"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public ReadOnly Property ConfigCPUx86RdBtn() As Boolean
        Get
            Return CType(Me("ConfigCPUx86RdBtn"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public ReadOnly Property ConfigCPUAMD64RdBtn() As Boolean
        Get
            Return CType(Me("ConfigCPUAMD64RdBtn"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public ReadOnly Property UserAcctsExcludeAllRdBtn() As Boolean
        Get
            Return CType(Me("UserAcctsExcludeAllRdBtn"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public ReadOnly Property UserAcctsExcludeLocalRdBtn() As Boolean
        Get
            Return CType(Me("UserAcctsExcludeLocalRdBtn"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public ReadOnly Property UserAcctsExcludeDomainRdBtn() As Boolean
        Get
            Return CType(Me("UserAcctsExcludeDomainRdBtn"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public ReadOnly Property UserAcctsExcludeDays() As String
        Get
            Return CType(Me("UserAcctsExcludeDays"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public ReadOnly Property UserAcctsExcludeDate() As String
        Get
            Return CType(Me("UserAcctsExcludeDate"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public ReadOnly Property UserAcctsIncludeAllRdBtn() As Boolean
        Get
            Return CType(Me("UserAcctsIncludeAllRdBtn"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public ReadOnly Property UserAcctsIncludeLocalRdBtn() As Boolean
        Get
            Return CType(Me("UserAcctsIncludeLocalRdBtn"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public ReadOnly Property UserAcctsIncludeDomainRdBtn() As Boolean
        Get
            Return CType(Me("UserAcctsIncludeDomainRdBtn"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public ReadOnly Property UserAcctsIncludeSelectedUsersRdBtn() As Boolean
        Get
            Return CType(Me("UserAcctsIncludeSelectedUsersRdBtn"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("F")>  _
    Public ReadOnly Property LocalDriveLetterDataShare() As String
        Get
            Return CType(Me("LocalDriveLetterDataShare"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public ReadOnly Property LocalDriveDataShareChkBx() As Boolean
        Get
            Return CType(Me("LocalDriveDataShareChkBx"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public ReadOnly Property BackupBackupRdBtn() As Boolean
        Get
            Return CType(Me("BackupBackupRdBtn"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public ReadOnly Property BackupRestoreRdBtn() As Boolean
        Get
            Return CType(Me("BackupRestoreRdBtn"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public ReadOnly Property BackupMethodUser() As Boolean
        Get
            Return CType(Me("BackupMethodUser"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public ReadOnly Property LocalLogDataDriveChkBx() As Boolean
        Get
            Return CType(Me("LocalLogDataDriveChkBx"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public ReadOnly Property MonitoringEnableBareTailLogChkBx() As Boolean
        Get
            Return CType(Me("MonitoringEnableBareTailLogChkBx"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("x86")>  _
    Public ReadOnly Property Usmt5Exex86Folder() As String
        Get
            Return CType(Me("Usmt5Exex86Folder"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Amd64")>  _
    Public ReadOnly Property Usmt5ExeAmd64Folder() As String
        Get
            Return CType(Me("Usmt5ExeAmd64Folder"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public ReadOnly Property BackupSourceOSWin8RdBtn() As Boolean
        Get
            Return CType(Me("BackupSourceOSWin8RdBtn"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public ReadOnly Property BackupTargetOSWin8RdBtn() As Boolean
        Get
            Return CType(Me("BackupTargetOSWin8RdBtn"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("\CustomXML")>  _
    Public ReadOnly Property XmlCustomFilesFolder() As String
        Get
            Return CType(Me("XmlCustomFilesFolder"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("\\<ServerName>\<Share>$")>  _
    Public ReadOnly Property UNCUsmtDrivePath() As String
        Get
            Return CType(Me("UNCUsmtDrivePath"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("USMT1903")>  _
    Public ReadOnly Property USMTFolder() As String
        Get
            Return CType(Me("USMTFolder"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("DataStore")>  _
    Public ReadOnly Property DataStoreFolder() As String
        Get
            Return CType(Me("DataStoreFolder"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("\MigApp.xml")>  _
    Public ReadOnly Property MigAppXMLFile() As String
        Get
            Return CType(Me("MigAppXMLFile"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("\MigUserShared.xml")>  _
    Public ReadOnly Property MigUserXMLFile() As String
        Get
            Return CType(Me("MigUserXMLFile"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("\MigDocs.xml")>  _
    Public ReadOnly Property MigDocsXMLFile() As String
        Get
            Return CType(Me("MigDocsXMLFile"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("\CustApp.xml")>  _
    Public ReadOnly Property CustAppXMLFile() As String
        Get
            Return CType(Me("CustAppXMLFile"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("\CustUser.xml")>  _
    Public ReadOnly Property CustUserXMLFile() As String
        Get
            Return CType(Me("CustUserXMLFile"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("\NetworkPrinters.xml")>  _
    Public ReadOnly Property NetworkPrinterXMLFile() As String
        Get
            Return CType(Me("NetworkPrinterXMLFile"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("\ExcludeDrives_D_to_Z.xml")>  _
    Public ReadOnly Property ExcludeDrivesXMLFile() As String
        Get
            Return CType(Me("ExcludeDrivesXMLFile"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("\ExcludeSystemFolders.xml")>  _
    Public ReadOnly Property ExcludeSystemFoldersXMLFile() As String
        Get
            Return CType(Me("ExcludeSystemFoldersXMLFile"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("\ConfigS.xml")>  _
    Public ReadOnly Property ConfigSXMLFile() As String
        Get
            Return CType(Me("ConfigSXMLFile"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("\ConfigL.xml")>  _
    Public ReadOnly Property ConfigLXMLFile() As String
        Get
            Return CType(Me("ConfigLXMLFile"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("\Custom1.xml")>  _
    Public ReadOnly Property Cust1XMLFIle() As String
        Get
            Return CType(Me("Cust1XMLFIle"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("\")>  _
    Public ReadOnly Property Cust2XMLFile() As String
        Get
            Return CType(Me("Cust2XMLFile"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("\")>  _
    Public ReadOnly Property Cust3XMLFile() As String
        Get
            Return CType(Me("Cust3XMLFile"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("\\MDT01")>  _
    Public ReadOnly Property UNCServerFolder() As String
        Get
            Return CType(Me("UNCServerFolder"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public ReadOnly Property XMLConfigCust1ChkBx() As String
        Get
            Return CType(Me("XMLConfigCust1ChkBx"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public ReadOnly Property XMLConfigCust2ChkBx() As String
        Get
            Return CType(Me("XMLConfigCust2ChkBx"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public ReadOnly Property XMLConfigCust3ChkBx() As String
        Get
            Return CType(Me("XMLConfigCust3ChkBx"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("\test")>  _
    Public ReadOnly Property UNCShareFolder() As String
        Get
            Return CType(Me("UNCShareFolder"),String)
        End Get
    End Property
End Class

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.USMTGUI.Settings
            Get
                Return Global.USMTGUI.Settings.Default
            End Get
        End Property
    End Module
End Namespace
